# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@1.0.11     
      
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.7
        with:
           inlineScript: | 
             az login  --service-principal -u "ef11f03c-1933-4e1d-a4ba-af7073812062" -p "pOD8Q~LS37_dPla0dJsH3YNzpOLz4VtBfJD14c9U" --tenant "d5446430-c01f-4347-96cc-e79521dcd885"
             az account show
             az acr login --name acrsonali
             
         

     
      - name: Azure Container Registry Build
        uses: Azure/acr-build@v1
        with:
          service_principal: "ef11f03c-1933-4e1d-a4ba-af7073812062"
          service_principal_password: "pOD8Q~LS37_dPla0dJsH3YNzpOLz4VtBfJD14c9U"
          tenant:  "d5446430-c01f-4347-96cc-e79521dcd885"
          registry: "acrsonali"
          repository: "acrsonali.azurecr.io"
          image: "nginx:latest"
